#remote_theme: "jekyll/minima@1e8a445"
#minima:

theme: minima

# Set the Minima theme's skin to dark
minima:
  skin: "dark"

nav:
  - title: Home
    url: "/"
  - title: Documentation
    url: "/docs/"
  - title: Integrations
    url: "/integrations/"
