theme: slate  # Using the Slate theme

# Navigation links - Slate uses pages for navigation, so link directly to pages
header_pages:
  - title: Home
    url: "/"
  - title: Documentation
    url: "/docs/"
  - title: Integrations
    url: "/integrations/"
